// AUTO-GENERATED by scripts/amoytestnet/roitest.js
// Network: polygonAmoy | Deployed: 2/6/2026, 7:56:56 am

const CONTRACT_ADDRESS        = "0xfF1B10d861EEa7a6Ae42e0bF6456365B0ca3fd60";
const TOKEN_ADDRESS           = "0xd97a2D5dc162B4cfaf5800ceCCcE9fC495370eC0";
const TOKEN_ADDRESS_JIGGY     = "";
const TOKEN_ADDRESS_PANWORLD  = "";
const ROUTER_ADDRESS          = "0x85eaBB2740eD2f9e3b53c51D8e1E7BdA53672825";
const FACTORY_ADDRESS         = "0xa5d020Eb5a4D537f56F7314d2359f7770DE01a48";
const WETH_ADDRESS            = "0x7Bd0A72d3A07353C91dDA48D2B78454248d281E6";
const DEPLOY_BLOCK            = 39424326;
const FACET_ADDRESS           = "0xce4785F49Fc0C625d6c93ad9cBa7B95d6f11A91f";
const ROI_FACET_ADDRESS       = "0xCF32D659E27e8cBfa3C4F62Bb53269099393edC8";

const CONTRACT_ABI = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_router",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_factory",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_weth",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_platformToken",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "facet_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "roiFacet_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AlreadyClaimed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "AlreadyRemoved",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CannotReferSelf",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ClaimLPFirst",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CommissionTransferFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ETHReturnFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ETHWithdrawFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientContractTokenBalance",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientTokenBalance",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidDuration",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidDurationIndex",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidPackageAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidStreakLevel",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTierIndex",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidTokenAddress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LPAlreadyClaimed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LPPullFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LPStillLocked",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "LPTransferFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MustSendETH",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "MustSpecifyTokenAmount",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoETHToWithdraw",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoLPTokens",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NoTokensToWithdraw",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NothingToClaim",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PoolNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PriceDeviationTooHigh",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PriceUnavailable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "Reentrant",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReferrerNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StakingRewardTransferFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SurplusTransferFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TWAPStale",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenAlreadyRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenDelisted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenInProgress",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenNotRegistered",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenReturnFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenTWAPStale",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenTransferFailed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenWithdrawFailed",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "level",
        "type": "uint256"
      }
    ],
    "name": "CommissionPaid",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "ethAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lpTokens",
        "type": "uint256"
      }
    ],
    "name": "Invested",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lpAmount",
        "type": "uint256"
      }
    ],
    "name": "LPClaimed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lpAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "ethReturned",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "tokensReturned",
        "type": "uint256"
      }
    ],
    "name": "LPRemoved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lpAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newUnlockTime",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "durationDays",
        "type": "uint256"
      }
    ],
    "name": "LPRestaked",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "ethAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "tokenAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "lpReceived",
        "type": "uint256"
      }
    ],
    "name": "PoolSeeded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "tokensAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "ethEquivalent",
        "type": "uint256"
      }
    ],
    "name": "ROIClaimed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "tokensAmount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "ethEquivalent",
        "type": "uint256"
      }
    ],
    "name": "StakingRewardClaimed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "price",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "TWAPUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "tokenAddress",
        "type": "address"
      }
    ],
    "name": "TokenFeatured",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "tokenAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "label",
        "type": "string"
      }
    ],
    "name": "TokenInProgressSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "tokenAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "symbol",
        "type": "string"
      }
    ],
    "name": "TokenRegistered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "tokenAddress",
        "type": "address"
      }
    ],
    "name": "TokenRemoved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "tokenAddress",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "name",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "symbol",
        "type": "string"
      }
    ],
    "name": "TokenUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "referrer",
        "type": "address"
      }
    ],
    "name": "UserRegistered",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_tokenAddress",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "_name",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_symbol",
        "type": "string"
      }
    ],
    "name": "addToken",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "claimAllROI",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_lockIndex",
        "type": "uint256"
      }
    ],
    "name": "claimLP",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "investor",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "lockIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "level",
        "type": "uint8"
      }
    ],
    "name": "claimROIFromStream",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "claimStakingReward",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_lockIndex",
        "type": "uint256"
      }
    ],
    "name": "claimStakingRewardForLock",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "featuredToken",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getActiveDirectReferralCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      }
    ],
    "name": "getActiveROIStreams",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "investor",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "lockIndex",
            "type": "uint64"
          },
          {
            "internalType": "uint8",
            "name": "level",
            "type": "uint8"
          }
        ],
        "internalType": "struct StreamRef[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getAllRegisteredUsers",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getClaimRecords",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint128",
            "name": "tokensAmount",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "ethEquivalent",
            "type": "uint128"
          },
          {
            "internalType": "uint64",
            "name": "ts",
            "type": "uint64"
          }
        ],
        "internalType": "struct ClaimRecord[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getCommissionRecords",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "from",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "ts",
            "type": "uint64"
          },
          {
            "internalType": "uint8",
            "name": "level",
            "type": "uint8"
          },
          {
            "internalType": "uint128",
            "name": "amount",
            "type": "uint128"
          }
        ],
        "internalType": "struct CommissionRecord[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      }
    ],
    "name": "getContractTokenBalance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      }
    ],
    "name": "getDirectRefsInfo",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "addr",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "totalInvested",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "directRefCount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "remainingCap",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalCap",
            "type": "uint256"
          }
        ],
        "internalType": "struct DirectRefInfo[]",
        "name": "result",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getInvestRecords",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "token",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "ts",
            "type": "uint64"
          },
          {
            "internalType": "uint128",
            "name": "ethAmount",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "lpTokens",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "poolBuyTokens",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "totalTokens",
            "type": "uint128"
          }
        ],
        "internalType": "struct InvestRecord[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getLPEventRecords",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "token",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "ts",
            "type": "uint64"
          },
          {
            "internalType": "bool",
            "name": "isClaim",
            "type": "bool"
          },
          {
            "internalType": "uint128",
            "name": "lpAmount",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "ethReturned",
            "type": "uint128"
          }
        ],
        "internalType": "struct LPEventRecord[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getMissedRecords",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "from",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "ts",
            "type": "uint64"
          },
          {
            "internalType": "uint8",
            "name": "level",
            "type": "uint8"
          },
          {
            "internalType": "uint8",
            "name": "reason",
            "type": "uint8"
          },
          {
            "internalType": "uint128",
            "name": "amount",
            "type": "uint128"
          }
        ],
        "internalType": "struct MissedRecord[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getPlatformStats",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "_totalUsers",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_totalEthInvested",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_totalStakingRewardsPaidETH",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      }
    ],
    "name": "getPriceHistory",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint64",
            "name": "ts",
            "type": "uint64"
          },
          {
            "internalType": "uint112",
            "name": "resETH",
            "type": "uint112"
          },
          {
            "internalType": "uint112",
            "name": "resToken",
            "type": "uint112"
          }
        ],
        "internalType": "struct PriceSnap[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "investor",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "lockIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "level",
        "type": "uint8"
      }
    ],
    "name": "getROIAccrued",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getROIClaimRecords",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint128",
            "name": "tokensAmount",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "ethEquivalent",
            "type": "uint128"
          },
          {
            "internalType": "uint64",
            "name": "ts",
            "type": "uint64"
          }
        ],
        "internalType": "struct ClaimRecord[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      }
    ],
    "name": "getROIData",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "liveETH",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "pendingETH",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      }
    ],
    "name": "getROIPending",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "total",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "investor",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "lockIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint8",
        "name": "level",
        "type": "uint8"
      }
    ],
    "name": "getROIStreamInfo",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "recipient",
            "type": "address"
          },
          {
            "internalType": "uint64",
            "name": "recipientSince",
            "type": "uint64"
          },
          {
            "internalType": "bool",
            "name": "ended",
            "type": "bool"
          },
          {
            "internalType": "uint128",
            "name": "roiPaidETH",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "capETH",
            "type": "uint128"
          }
        ],
        "internalType": "struct ROIStream",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_owner",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_ref",
        "type": "address"
      }
    ],
    "name": "getRefLabel",
    "outputs": [
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getReferrals",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getReferrer",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getRegisteredTokens",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "ethInvestedWei",
        "type": "uint256"
      }
    ],
    "name": "getStakingRatesForAmount",
    "outputs": [
      {
        "internalType": "uint256[6]",
        "name": "durSecs",
        "type": "uint256[6]"
      },
      {
        "internalType": "uint256[6]",
        "name": "ratesPPM",
        "type": "uint256[6]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getStakingReward",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "totalAccumulated",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "previewNewTokens",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "lifetimeClaimed",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getTWAPPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_tokenAddress",
        "type": "address"
      }
    ],
    "name": "getToken",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "tokenAddress",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "symbol",
            "type": "string"
          },
          {
            "internalType": "uint256",
            "name": "addedAt",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "removed",
            "type": "bool"
          },
          {
            "internalType": "string",
            "name": "inProgressLabel",
            "type": "string"
          }
        ],
        "internalType": "struct Token",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      }
    ],
    "name": "getTradeHistory",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint64",
            "name": "ts",
            "type": "uint64"
          },
          {
            "internalType": "bool",
            "name": "isBuy",
            "type": "bool"
          },
          {
            "internalType": "uint128",
            "name": "ethAmt",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "tokAmt",
            "type": "uint128"
          }
        ],
        "internalType": "struct TradeSnap[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getUserCommissionStats",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "earned",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "totalCap",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "remainingCap",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "active",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getUserLPLocks",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "token",
            "type": "address"
          },
          {
            "internalType": "bool",
            "name": "claimed",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "removed",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "lpAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "unlockTime",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "ethInvested",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "lockedAt",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "rewardClaimedETH",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "tokensAccumulated",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "totalTokensClaimed",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "rewardRatePPM",
            "type": "uint256"
          },
          {
            "internalType": "uint8[6]",
            "name": "restakeCounts",
            "type": "uint8[6]"
          },
          {
            "internalType": "uint256",
            "name": "streakBaseEth",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "commissionsCapUsed",
            "type": "uint256"
          }
        ],
        "internalType": "struct LPLock[]",
        "name": "",
        "type": "tuple[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      }
    ],
    "name": "getWealthParams",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint256",
            "name": "refEarnings",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "platformTokenPriceEth",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "lpLockDuration",
            "type": "uint256"
          },
          {
            "components": [
              {
                "internalType": "uint256",
                "name": "ethInvested",
                "type": "uint256"
              },
              {
                "internalType": "uint256",
                "name": "rewardRatePPM",
                "type": "uint256"
              },
              {
                "internalType": "uint256",
                "name": "lockedAt",
                "type": "uint256"
              },
              {
                "internalType": "uint256",
                "name": "unlockTime",
                "type": "uint256"
              },
              {
                "internalType": "bool",
                "name": "removed",
                "type": "bool"
              },
              {
                "internalType": "uint256",
                "name": "tokensAccumulated",
                "type": "uint256"
              },
              {
                "internalType": "uint256",
                "name": "lpAmount",
                "type": "uint256"
              },
              {
                "internalType": "uint256",
                "name": "reserveETH",
                "type": "uint256"
              },
              {
                "internalType": "uint256",
                "name": "totalLPSupply",
                "type": "uint256"
              }
            ],
            "internalType": "struct WealthLockParam[]",
            "name": "locks",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct WealthParams",
        "name": "p",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      }
    ],
    "name": "invest",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "minDirectReferralInvestment",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "platformToken",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "referralCommissionRates",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_referrer",
        "type": "address"
      }
    ],
    "name": "register",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_lockIndex",
        "type": "uint256"
      }
    ],
    "name": "removeLP",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_lockIndex",
        "type": "uint256"
      }
    ],
    "name": "removeLPDirect",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_tokenAddress",
        "type": "address"
      }
    ],
    "name": "removeToken",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_lockIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_durationDays",
        "type": "uint256"
      }
    ],
    "name": "restakeLP",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_tokenAmount",
        "type": "uint256"
      }
    ],
    "name": "seedPool",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_tokenAddress",
        "type": "address"
      }
    ],
    "name": "setFeaturedToken",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      }
    ],
    "name": "setMinDirectReferralInvestment",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_ref",
        "type": "address"
      },
      {
        "internalType": "bytes",
        "name": "_label",
        "type": "bytes"
      }
    ],
    "name": "setRefLabel",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "durationIdx",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "tierIdx",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "streakLevel",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "rate",
        "type": "uint256"
      }
    ],
    "name": "setStakingRates",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_tokenAddress",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "_label",
        "type": "string"
      }
    ],
    "name": "setTokenInProgress",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "ethWei",
        "type": "uint256"
      },
      {
        "internalType": "bool",
        "name": "valid",
        "type": "bool"
      }
    ],
    "name": "setValidPackage",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_minTokensOut",
        "type": "uint256"
      }
    ],
    "name": "swapBuy",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_tokensIn",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_minEthOut",
        "type": "uint256"
      }
    ],
    "name": "swapSell",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "totalMissedCommissions",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "updateTWAP",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_tokenAddress",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "_name",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "_symbol",
        "type": "string"
      }
    ],
    "name": "updateToken",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      }
    ],
    "name": "updateTokenTWAP",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "userTotalInvested",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "users",
    "outputs": [
      {
        "internalType": "address",
        "name": "userAddress",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "referrer",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "isRegistered",
        "type": "bool"
      },
      {
        "internalType": "uint256",
        "name": "registeredAt",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "withdrawETH",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_token",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "withdrawToken",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
];
