const hre  = require("hardhat");
const fs   = require("fs");
const path = require("path");

// Uniswap V2 addresses (hardhat localhost / mainnet fork)
const UNI_ROUTER  = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D";
const UNI_FACTORY = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f";
const UNI_WETH    = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";

async function main() {
  const network = hre.network.name;
  console.log(`\nDeploying to ${network}...`);

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deployer:", deployer.address);

  const balance = await hre.ethers.provider.getBalance(deployer.address);
  console.log("Balance:", hre.ethers.formatEther(balance), "ETH\n");

  console.log("Router: ", UNI_ROUTER);
  console.log("Factory:", UNI_FACTORY);
  console.log("WETH:   ", UNI_WETH);
  console.log();

  // ── Deploy HordexToken ──
  const HordexToken = await hre.ethers.getContractFactory("HordexToken");
  const hordexToken = await HordexToken.deploy("Hordex Token", "HORDEX", 10_000_000);
  await hordexToken.waitForDeployment();
  const tokenAddress = await hordexToken.getAddress();
  console.log("HordexToken deployed to:", tokenAddress);

  // ── Deploy Liquidity ──
  const Liquidity = await hre.ethers.getContractFactory("Liquidity");
  const liquidity = await Liquidity.deploy(UNI_ROUTER, UNI_FACTORY, UNI_WETH, tokenAddress);
  await liquidity.waitForDeployment();
  const liquidityAddress = await liquidity.getAddress();
  console.log("Liquidity  deployed to:", liquidityAddress);

  const totalSupply = await hordexToken.totalSupply();

  // ── Seed Liquidity contract with full token supply ──
  // invest() checks balanceOf(address(this)) > 0 and uses platform tokens for addLiquidityETH.
  console.log("\nTransferring", hre.ethers.formatEther(totalSupply), "HORDEX to Liquidity contract...");
  const tx1 = await hordexToken.transfer(liquidityAddress, totalSupply);
  await tx1.wait();
  console.log("  Token transfer confirmed ✓");

  // ── Auto-update contract-config.js ──
  const artifact = hre.artifacts.readArtifactSync("Liquidity");
  const configPath = path.join(__dirname, "..", "contract-config.js");
  const configContent =
`// AUTO-GENERATED by scripts/deploy.js — do not edit manually
// Network: ${network} | Deployed: ${new Date().toLocaleString()}

const CONTRACT_ADDRESS  = "${liquidityAddress}";
const TOKEN_ADDRESS     = "${tokenAddress}";
const ROUTER_ADDRESS    = "${UNI_ROUTER}";
const FACTORY_ADDRESS   = "${UNI_FACTORY}";
const WETH_ADDRESS      = "${UNI_WETH}";

const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;

  const frontendConfig = path.join(__dirname, "..", "frontend", "contract-config.js");
  fs.writeFileSync(configPath,     configContent);
  fs.writeFileSync(frontendConfig, configContent);
  console.log("\ncontract-config.js updated ✓ (root + frontend)");

  console.log("\n── Deployment Summary ──────────────────────────");
  console.log("HordexToken:", tokenAddress);
  console.log("Liquidity:  ", liquidityAddress);
  console.log("Router:     ", UNI_ROUTER);
  console.log("Factory:    ", UNI_FACTORY);
  console.log("WETH:       ", UNI_WETH);
  console.log("────────────────────────────────────────────────\n");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});