const hre  = require("hardhat");
const fs   = require("fs");
const path = require("path");

const UNI_ROUTER  = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D";
const UNI_FACTORY = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f";
const UNI_WETH    = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";

const USDT_PER_ETH = 1000;
const PACKAGE_ETH  = hre.ethers.parseEther("0.025"); // 25 USDT

// BPS rates applied to A40 (= 20% of T). Divide by 500 for % of total investment.
const COMM_RATES_BPS = [5000, 2500, 1000, 300, 250, 225, 200, 200, 175, 150];

//  Referral tree:
//  account[0]  →  [1, 2, 3]
//  account[1]  →  [4, 5]
//  account[4]  →  [6]
//  Total: 7 accounts (0–6)

const groups = [
  { referrer: 0, children: [1, 2, 3] },
  { referrer: 1, children: [4, 5]    },
  { referrer: 4, children: [6]       },
];

const referrerOf = new Map();
referrerOf.set(0, null);
for (const g of groups) {
  for (const c of g.children) referrerOf.set(c, g.referrer);
}

const TOTAL_ACCOUNTS = 7;

function toUSDT(ethBigInt) {
  return (parseFloat(hre.ethers.formatEther(ethBigInt)) * USDT_PER_ETH).toFixed(2);
}

function sep(char = "─", len = 60) { return char.repeat(len); }

async function main() {
  const signers  = await hre.ethers.getSigners();
  const deployer = signers[0];
  const network  = hre.network.name;

  if (signers.length < TOTAL_ACCOUNTS)
    throw new Error(`Need ${TOTAL_ACCOUNTS} signers — only ${signers.length} available.`);

  console.log(sep("═"));
  console.log("  HALFSIMULATE — Deploy · Referral Tree · Investments");
  console.log(sep("═"));
  console.log(`  Network  : ${network}`);
  console.log(`  Deployer : ${deployer.address}`);
  console.log(`  Accounts : ${TOTAL_ACCOUNTS} (0–6)\n`);

  // ─────────────────────────────────────────────────────────────
  // PHASE 1 — DEPLOY
  // ─────────────────────────────────────────────────────────────
  console.log(sep());
  console.log("  PHASE 1 — DEPLOY");
  console.log(sep());

  const HordexToken = await hre.ethers.getContractFactory("HordexToken");
  const hordexToken = await HordexToken.deploy("Hordex Token", "HORDEX", 10_000_000);
  await hordexToken.waitForDeployment();
  const tokenAddress = await hordexToken.getAddress();
  console.log(`  HordexToken : ${tokenAddress}`);

  const Liquidity = await hre.ethers.getContractFactory("Liquidity");
  const liquidity = await Liquidity.deploy(UNI_ROUTER, UNI_FACTORY, UNI_WETH, tokenAddress);
  await liquidity.waitForDeployment();
  const liquidityAddress = await liquidity.getAddress();
  console.log(`  Liquidity   : ${liquidityAddress}`);

  const totalSupply = await hordexToken.totalSupply();
  await (await hordexToken.transfer(liquidityAddress, totalSupply)).wait();
  console.log(`  Token supply (${hre.ethers.formatEther(totalSupply)} HORDEX) → Liquidity ✓`);

  await (await liquidity.addToken(tokenAddress, "Hordex Token", "HORDEX")).wait();
  console.log(`  HordexToken registered in platform ✓`);

  const seedETH    = hre.ethers.parseEther("100");
  const seedTokens = hre.ethers.parseEther("100000");
  await (await liquidity.seedPool(tokenAddress, seedTokens, { value: seedETH })).wait();
  console.log(`  Uniswap pool seeded: 100 ETH + 100,000 HORDEX  (1 HORDEX = $1.00 USDT) ✓`);

  const artifact      = hre.artifacts.readArtifactSync("Liquidity");
  const configContent =
`// AUTO-GENERATED by scripts/halfsimulate.js — do not edit manually
// Network: ${network} | Deployed: ${new Date().toLocaleString()}

const CONTRACT_ADDRESS  = "${liquidityAddress}";
const TOKEN_ADDRESS     = "${tokenAddress}";
const ROUTER_ADDRESS    = "${UNI_ROUTER}";
const FACTORY_ADDRESS   = "${UNI_FACTORY}";
const WETH_ADDRESS      = "${UNI_WETH}";

const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;
  fs.writeFileSync(path.join(__dirname, "..", "contract-config.js"),             configContent);
  fs.writeFileSync(path.join(__dirname, "..", "frontend", "contract-config.js"), configContent);
  console.log(`  contract-config.js written ✓ (root + frontend)\n`);

  // ─────────────────────────────────────────────────────────────
  // PHASE 2 — REGISTER
  // ─────────────────────────────────────────────────────────────
  console.log(sep());
  console.log("  PHASE 2 — REGISTER  (account[0] pre-registered in constructor)");
  console.log(sep());

  for (const g of groups) {
    console.log(
      `\n  account[${g.referrer}]  →  ${g.children.length} referral(s)  [${g.children.join(", ")}]`
    );
    for (const idx of g.children) {
      const ct = new hre.ethers.Contract(liquidityAddress, artifact.abi, signers[idx]);
      await (await ct.register(signers[g.referrer].address)).wait();
      console.log(`    [${idx}] ${signers[idx].address}  ← [${g.referrer}] ✓`);
    }
  }

  const totalRegistered = groups.reduce((s, g) => s + g.children.length, 0);
  console.log(`\n  ${totalRegistered} accounts registered ✓\n`);

  // ─────────────────────────────────────────────────────────────
  // PHASE 3 — INVEST  (BFS order: parents before children)
  // ─────────────────────────────────────────────────────────────
  console.log(sep());
  console.log("  PHASE 3 — INVESTMENTS  (25 USDT = 0.025 ETH each, all 7 accounts)");
  console.log(sep());

  const iface = new hre.ethers.Interface([
    "event CommissionPaid(address indexed recipient, address indexed from, uint256 amount, uint256 level)",
  ]);

  // BFS order: account[0] first, then each group's children in order
  const investOrder = [0, ...groups.flatMap(g => g.children)];

  let totalInvested    = 0n;
  let totalCommissions = 0n;

  for (const idx of investOrder) {
    const account = signers[idx];
    const ct      = new hre.ethers.Contract(liquidityAddress, artifact.abi, account);

    const tx      = await ct.invest(tokenAddress, { value: PACKAGE_ETH });
    const receipt = await tx.wait();

    totalInvested += PACKAGE_ETH;

    const comms = [];
    for (const log of receipt.logs) {
      try {
        const parsed = iface.parseLog({ topics: log.topics, data: log.data });
        if (parsed?.name === "CommissionPaid") {
          comms.push({
            recipient : parsed.args.recipient,
            amount    : parsed.args.amount,
            level     : Number(parsed.args.level),
          });
        }
      } catch (_) {}
    }

    const txTotal     = comms.reduce((s, c) => s + c.amount, 0n);
    totalCommissions += txTotal;

    const refIdx   = referrerOf.get(idx);
    const refLabel = refIdx === null ? "no referrer" : `ref by [${refIdx}]`;
    console.log(`\n  account[${idx}]  ${account.address}  (${refLabel})`);
    console.log(`  ${sep("·", 56)}`);

    if (comms.length === 0) {
      console.log(`    (no commission events)`);
    } else {
      for (const c of comms) {
        const ratePct   = (COMM_RATES_BPS[c.level - 1] / 500).toFixed(2).replace(/\.?0+$/, "");
        const usdtAmt   = toUSDT(c.amount);
        const recvIdx   = signers.findIndex(s => s.address.toLowerCase() === c.recipient.toLowerCase());
        const isOwner   = recvIdx === 0;
        const recvLabel = isOwner
          ? `account[0]  (owner / platform)`
          : `account[${recvIdx}]  ${c.recipient.slice(0, 10)}…`;
        console.log(
          `    L${String(c.level).padEnd(2)}  ${String(ratePct).padStart(5)}% of T` +
          `  $${usdtAmt.padStart(7)} USDT  →  ${recvLabel}`
        );
      }
      console.log(`    ── total: $${toUSDT(txTotal)} USDT`);
    }
  }

  // ─────────────────────────────────────────────────────────────
  // SUMMARY
  // ─────────────────────────────────────────────────────────────
  console.log(`\n${sep("═")}`);
  console.log("  HALFSIMULATION COMPLETE");
  console.log(sep("═"));
  console.log(`  HordexToken    : ${tokenAddress}`);
  console.log(`  Liquidity      : ${liquidityAddress}`);
  console.log(`  Accounts       : ${investOrder.length}  (accounts[0..6])`);
  console.log(`  Package        : 25 USDT (0.025 ETH) each`);
  console.log(`  Total invested : $${toUSDT(totalInvested)} USDT`);
  console.log(`  Total comms    : $${toUSDT(totalCommissions)} USDT`);

  console.log(`\n  Tree structure:`);
  console.log(`  ${"REFERRER".padEnd(12)} ${"COUNT".padEnd(7)} CHILDREN`);
  console.log(`  ${sep("·", 36)}`);
  for (const g of groups) {
    console.log(
      `  account[${g.referrer}]    ` +
      `${String(g.children.length).padEnd(7)}` +
      `[${g.children.join(", ")}]`
    );
  }

  const contractETH = await hre.ethers.provider.getBalance(liquidityAddress);
  const contractTok = await hordexToken.balanceOf(liquidityAddress);
  console.log(`\n  Contract balances:`);
  console.log(`    ETH    : ${hre.ethers.formatEther(contractETH)}`);
  console.log(`    HORDEX : ${hre.ethers.formatEther(contractTok)}`);
  console.log(sep("═") + "\n");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
