const hre  = require("hardhat");
const fs   = require("fs");
const path = require("path");

const UNI_ROUTER  = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D";
const UNI_FACTORY = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f";
const UNI_WETH    = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";

async function main() {
  const [deployer] = await hre.ethers.getSigners();

  console.log("Deploying contracts with:", deployer.address);

  // Deploy HordexToken
  const HordexToken = await hre.ethers.getContractFactory("HordexToken");

  const token = await HordexToken.deploy(
    "HORDEX",
    "HORDEX",
    10_000_000
  );

  await token.waitForDeployment();

  const tokenAddress = await token.getAddress();

  console.log("HordexToken deployed:", tokenAddress);

  // Deploy Liquidity
  const Liquidity = await hre.ethers.getContractFactory("Liquidity");

  const liquidity = await Liquidity.deploy(
    UNI_ROUTER,
    UNI_FACTORY,
    UNI_WETH,
    tokenAddress
  );

  await liquidity.waitForDeployment();

  const liquidityAddress = await liquidity.getAddress();

  console.log("Liquidity deployed:", liquidityAddress);

  // ================================
  // TRANSFER FULL TOKEN SUPPLY
  // ================================

  const totalSupply = await token.totalSupply();

  console.log(
    "Transferring total supply:",
    hre.ethers.formatUnits(totalSupply, 18),
    "HORDEX"
  );

  const tx = await token.transfer(liquidityAddress, totalSupply);

  await tx.wait();

  // Verify balances
  const liquidityBalance = await token.balanceOf(liquidityAddress);
  const deployerBalance  = await token.balanceOf(deployer.address);

  console.log(
    "Liquidity contract token balance:",
    hre.ethers.formatUnits(liquidityBalance, 18)
  );

  console.log(
    "Deployer token balance:",
    hre.ethers.formatUnits(deployerBalance, 18)
  );

  if (liquidityBalance !== totalSupply) {
    throw new Error("Full supply transfer failed");
  }

  console.log("Full token supply transferred successfully ✓");

  // =====================================
  // UPDATE contract-config.js
  // =====================================

  const artifact = hre.artifacts.readArtifactSync("Liquidity");

  const network  = hre.network.name;

  const config =
`// AUTO-GENERATED by scripts/justdeploy.js — do not edit manually
// Network: ${network} | Deployed: ${new Date().toLocaleString()}

const CONTRACT_ADDRESS  = "${liquidityAddress}";
const TOKEN_ADDRESS     = "${tokenAddress}";
const ROUTER_ADDRESS    = "${UNI_ROUTER}";
const FACTORY_ADDRESS   = "${UNI_FACTORY}";
const WETH_ADDRESS      = "${UNI_WETH}";

const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;

  fs.writeFileSync(
    path.join(__dirname, "..", "contract-config.js"),
    config
  );

  fs.writeFileSync(
    path.join(__dirname, "..", "frontend", "contract-config.js"),
    config
  );

  console.log("contract-config.js updated ✓ (root + frontend)");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});