const hre  = require("hardhat");
const fs   = require("fs");
const path = require("path");

const UNI_ROUTER  = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D";
const UNI_FACTORY = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f";
const UNI_WETH    = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2";

const USDT_PER_ETH = 1000;
const PACKAGE_ETH  = hre.ethers.parseEther("0.1"); // 100 USDT

// BPS rates applied to A40 (= 20% of T). Divide by 500 for % of total investment.
const COMM_RATES_BPS = [5000, 2500, 1000, 300, 250, 225, 200, 200, 175, 150];

function toUSDT(ethBigInt) {
  return (parseFloat(hre.ethers.formatEther(ethBigInt)) * USDT_PER_ETH).toFixed(2);
}

function sep(char = "─", len = 60) { return char.repeat(len); }

async function main() {
  const signers  = await hre.ethers.getSigners();
  const deployer = signers[0];
  const network  = hre.network.name;

  console.log(sep("═"));
  console.log("  SIMULATE — Deploy · Referral Tree · Investments");
  console.log(sep("═"));
  console.log(`  Network  : ${network}`);
  console.log(`  Deployer : ${deployer.address}`);
  console.log(`  Accounts : ${signers.length} signers available\n`);

  // ─────────────────────────────────────────────────────────────
  // PHASE 1 — DEPLOY
  // ─────────────────────────────────────────────────────────────
  console.log(sep());
  console.log("  PHASE 1 — DEPLOY");
  console.log(sep());

  const tokenDefs = [
    { name: "Hordex Token",   symbol: "HORDEX"   },
    { name: "Jiggy Token",    symbol: "JIGGY"    },
    { name: "PanWorld Token", symbol: "PANWORLD" },
  ];
  const TOKEN_SUPPLY = 10_000_000;

  const HordexToken = await hre.ethers.getContractFactory("HordexToken");
  const deployedTokens = [];

  for (const def of tokenDefs) {
    const token = await HordexToken.deploy(def.name, def.symbol, TOKEN_SUPPLY);
    await token.waitForDeployment();
    const addr = await token.getAddress();
    deployedTokens.push({ ...def, contract: token, address: addr });
    console.log(`  ${def.symbol.padEnd(8)}: ${addr}`);
  }

  // Hordex is the platform token (used for staking rewards)
  const tokenAddress = deployedTokens[0].address;

  const LiquidityMath = await hre.ethers.getContractFactory("LiquidityMath");
  const liquidityMath = await LiquidityMath.deploy();
  await liquidityMath.waitForDeployment();
  const libAddress = await liquidityMath.getAddress();
  console.log(`  LiquidityMath   : ${libAddress}`);

  const LiquidityViewLib = await hre.ethers.getContractFactory("LiquidityViewLib", {
    libraries: { LiquidityMath: libAddress },
  });
  const liquidityViewLib = await LiquidityViewLib.deploy();
  await liquidityViewLib.waitForDeployment();
  const libViewAddress = await liquidityViewLib.getAddress();
  console.log(`  LiquidityViewLib: ${libViewAddress}`);

  const Liquidity = await hre.ethers.getContractFactory("Liquidity", {
    libraries: { LiquidityMath: libAddress, LiquidityViewLib: libViewAddress },
  });
  const liquidity = await Liquidity.deploy(UNI_ROUTER, UNI_FACTORY, UNI_WETH, tokenAddress);
  await liquidity.waitForDeployment();
  const liquidityAddress = await liquidity.getAddress();
  const deployTx      = liquidity.deploymentTransaction();
  const deployReceipt = await deployTx.wait();
  const deployBlock   = deployReceipt.blockNumber;
  console.log(`  Liquidity   : ${liquidityAddress}  (block ${deployBlock})`);

  // Transfer full supply of each token to Liquidity, register, and seed pool
  const seedETH    = hre.ethers.parseEther("100");
  const seedTokens = hre.ethers.parseEther("100000");

  for (const t of deployedTokens) {
    const supply = await t.contract.totalSupply();
    await (await t.contract.transfer(liquidityAddress, supply)).wait();
    console.log(`  Token supply (${hre.ethers.formatEther(supply)} ${t.symbol}) → Liquidity ✓`);

    await (await liquidity.addToken(t.address, t.name, t.symbol)).wait();
    console.log(`  ${t.symbol} registered in platform ✓`);

    await (await liquidity.seedPool(t.address, seedTokens, { value: seedETH })).wait();
    console.log(`  Uniswap pool seeded: 100 ETH + 100,000 ${t.symbol}  (1 ${t.symbol} = $1.00 USDT) ✓`);
  }

  // ─────────────────────────────────────────────────────────────
  // TWAP WARM-UP
  // updateTWAP needs two observations ≥ 30 min apart before
  // _twapReady = true.  On Hardhat, advance time manually.
  // ─────────────────────────────────────────────────────────────
  console.log(sep());
  console.log("  TWAP WARM-UP");
  console.log(sep());
  await (await liquidity.updateTWAP()).wait();
  console.log("  Observation 0 recorded ✓");
  await hre.network.provider.send("evm_increaseTime", [31 * 60]);
  await hre.network.provider.send("evm_mine");
  await (await liquidity.updateTWAP()).wait();
  console.log("  Time advanced 31 min · Observation 1 recorded ✓");
  console.log("  TWAP ready — staking rewards are claimable ✓\n");

  const artifact      = hre.artifacts.readArtifactSync("Liquidity");
  const configContent =
`// AUTO-GENERATED by scripts/simulate.js — do not edit manually
// Network: ${network} | Deployed: ${new Date().toLocaleString()}

const CONTRACT_ADDRESS        = "${liquidityAddress}";
const TOKEN_ADDRESS           = "${deployedTokens[0].address}";
const TOKEN_ADDRESS_JIGGY     = "${deployedTokens[1].address}";
const TOKEN_ADDRESS_PANWORLD  = "${deployedTokens[2].address}";
const ROUTER_ADDRESS          = "${UNI_ROUTER}";
const FACTORY_ADDRESS         = "${UNI_FACTORY}";
const WETH_ADDRESS            = "${UNI_WETH}";
const DEPLOY_BLOCK            = ${deployBlock};

const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;
  fs.writeFileSync(path.join(__dirname, "..", "contract-config.js"),             configContent);
  fs.writeFileSync(path.join(__dirname, "..", "frontend", "contract-config.js"), configContent);

  const indexPath = path.join(__dirname, "..", "frontend", "index.html");
  fs.writeFileSync(indexPath,
    fs.readFileSync(indexPath, "utf8")
      .replace(/contract-config\.js\?v=\d+/g, `contract-config.js?v=${Date.now()}`)
  );
  console.log(`  contract-config.js written ✓ (root + frontend)\n`);

  // ─────────────────────────────────────────────────────────────
  // Build spine tree
  //
  //  account[0]  → [1]       ( 1)  spine → [1]
  //  account[1]  → [2..11]   (10)  spine → [2]
  //  account[2]  → [12..20]  ( 9)  spine → [12]
  //  account[12] → [21..28]  ( 8)  spine → [21]
  //  account[21] → [29..35]  ( 7)  spine → [29]
  //  account[29] → [36..41]  ( 6)  spine → [36]
  //  account[36] → [42..46]  ( 5)  spine → [42]
  //  account[42] → [47..50]  ( 4)  spine → [47]
  //  account[47] → [51..53]  ( 3)  spine → [51]
  //  account[51] → [54..55]  ( 2)  spine → [54]
  //  account[54] → [56]      ( 1)  (leaf)
  //
  //  Total: 57 accounts (0–56).
  // ─────────────────────────────────────────────────────────────

  const groups = [];            // { referrer, children[] }
  const referrerOf = new Map(); // child index → referrer index
  referrerOf.set(0, null);

  {
    // account[0] → account[1] only
    groups.push({ referrer: 0, children: [1] });
    referrerOf.set(1, 0);

    // account[1] → 10 children, first child → 9, … down to 1
    let spineNode = 1;
    let next      = 2;
    for (let depth = 0; depth < 10; depth++) {
      const count    = 10 - depth;           // 10, 9, 8 … 1
      const children = [];
      for (let k = 0; k < count; k++) children.push(next++);
      groups.push({ referrer: spineNode, children });
      for (const c of children) referrerOf.set(c, spineNode);
      spineNode = children[0];               // spine continues via first child
    }
  }

  const TOTAL_ACCOUNTS = 57; // 0..56
  if (signers.length < TOTAL_ACCOUNTS)
    throw new Error(`Need ${TOTAL_ACCOUNTS} signers — only ${signers.length} available.`);

  // ─────────────────────────────────────────────────────────────
  // PHASE 2 — REGISTER
  // ─────────────────────────────────────────────────────────────
  console.log(sep());
  console.log("  PHASE 2 — REGISTER  (account[0] pre-registered in constructor)");
  console.log(sep());

  for (const g of groups) {
    const first = g.children[0];
    const last  = g.children[g.children.length - 1];
    console.log(
      `\n  account[${String(g.referrer).padStart(2)}]  →  ` +
      `${g.children.length} referral(s)  [${String(first).padStart(2)}..${String(last).padStart(2)}]`
    );
    for (const idx of g.children) {
      const ct = new hre.ethers.Contract(liquidityAddress, artifact.abi, signers[idx]);
      await (await ct.register(signers[g.referrer].address)).wait();
      console.log(
        `    [${String(idx).padStart(2)}] ${signers[idx].address}` +
        `  ← [${String(g.referrer).padStart(2)}] ✓`
      );
    }
  }

  const totalRegistered = groups.reduce((s, g) => s + g.children.length, 0);
  console.log(`\n  ${totalRegistered} accounts registered ✓\n`);

  // ─────────────────────────────────────────────────────────────
  // PHASE 3 — INVEST  (BFS order: parents before children)
  // ─────────────────────────────────────────────────────────────
  console.log(sep());
  console.log("  PHASE 3 — INVESTMENTS  (100 USDT = 0.1 ETH each, all 57 accounts)");
  console.log(sep());

  const iface = new hre.ethers.Interface([
    "event CommissionPaid(address indexed recipient, address indexed from, uint256 amount, uint256 level)",
  ]);

  // BFS order: account[0] first, then each group's children in order
  const investOrder = [0, ...groups.flatMap(g => g.children)];

  let totalInvested    = 0n;
  let totalCommissions = 0n;

  for (const idx of investOrder) {
    const account = signers[idx];
    const ct      = new hre.ethers.Contract(liquidityAddress, artifact.abi, account);

    const tx      = await ct.invest(tokenAddress, { value: PACKAGE_ETH });
    const receipt = await tx.wait();

    totalInvested += PACKAGE_ETH;

    // Parse CommissionPaid events
    const comms = [];
    for (const log of receipt.logs) {
      try {
        const parsed = iface.parseLog({ topics: log.topics, data: log.data });
        if (parsed?.name === "CommissionPaid") {
          comms.push({
            recipient : parsed.args.recipient,
            amount    : parsed.args.amount,
            level     : Number(parsed.args.level),
          });
        }
      } catch (_) {}
    }

    const txTotal     = comms.reduce((s, c) => s + c.amount, 0n);
    totalCommissions += txTotal;

    const refIdx   = referrerOf.get(idx);
    const refLabel = refIdx === null ? "no referrer" : `ref by [${String(refIdx).padStart(2)}]`;
    console.log(
      `\n  account[${String(idx).padStart(2)}]  ${account.address}  (${refLabel})`
    );
    console.log(`  ${sep("·", 56)}`);

    if (comms.length === 0) {
      console.log(`    (no commission events)`);
    } else {
      for (const c of comms) {
        const ratePct  = (COMM_RATES_BPS[c.level - 1] / 500).toFixed(2).replace(/\.?0+$/, "");
        const usdtAmt  = toUSDT(c.amount);
        const recvIdx  = signers.findIndex(
          s => s.address.toLowerCase() === c.recipient.toLowerCase()
        );
        const isOwner  = recvIdx === 0;
        const recvLabel = isOwner
          ? `account[00]  (owner / platform)`
          : `account[${String(recvIdx).padStart(2)}]  ${c.recipient.slice(0, 10)}…`;
        console.log(
          `    L${String(c.level).padEnd(2)}  ${String(ratePct).padStart(5)}% of T` +
          `  $${usdtAmt.padStart(7)} USDT  →  ${recvLabel}`
        );
      }
      console.log(`    ── total: $${toUSDT(txTotal)} USDT`);
    }
  }

  // ─────────────────────────────────────────────────────────────
  // SUMMARY
  // ─────────────────────────────────────────────────────────────
  console.log(`\n${sep("═")}`);
  console.log("  SIMULATION COMPLETE");
  console.log(sep("═"));
  for (const t of deployedTokens) {
    console.log(`  ${t.symbol.padEnd(10)}: ${t.address}`);
  }
  console.log(`  Liquidity      : ${liquidityAddress}`);
  console.log(`  Accounts       : ${investOrder.length}  (accounts[0..56])`);
  console.log(`  Package        : 100 USDT (0.1 ETH) each`);
  console.log(`  Total invested : $${toUSDT(totalInvested)} USDT`);
  console.log(`  Total comms    : $${toUSDT(totalCommissions)} USDT`);

  console.log(`\n  Tree structure:`);
  console.log(`  ${"REFERRER".padEnd(14)} ${"COUNT".padEnd(7)} RANGE`);
  console.log(`  ${sep("·", 38)}`);
  for (const g of groups) {
    const first = g.children[0], last = g.children[g.children.length - 1];
    console.log(
      `  account[${String(g.referrer).padStart(2)}]    ` +
      `${String(g.children.length).padEnd(7)}` +
      `[${String(first).padStart(2)}..${String(last).padStart(2)}]`
    );
  }

  const contractETH = await hre.ethers.provider.getBalance(liquidityAddress);
  console.log(`\n  Contract balances:`);
  console.log(`    ETH      : ${hre.ethers.formatEther(contractETH)}`);
  for (const t of deployedTokens) {
    const bal = await t.contract.balanceOf(liquidityAddress);
    console.log(`    ${t.symbol.padEnd(8)}: ${hre.ethers.formatEther(bal)}`);
  }
  console.log(sep("═") + "\n");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
